//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biciklista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biciklista()
        {
            this.Lista_Trka = new HashSet<Lista_Trka>();
            this.Mentalne_Sposobnosti = new HashSet<Mentalne_Sposobnosti>();
            this.Prirodne_Sposobnosti = new HashSet<Prirodne_Sposobnosti>();
            this.Profilisanje_Profila_Vozaca = new HashSet<Profilisanje_Profila_Vozaca>();
            this.Sezonas = new HashSet<Sezona>();
            this.Sprint_Test = new HashSet<Sprint_Test>();
            this.Test_Kriticne_Snage = new HashSet<Test_Kriticne_Snage>();
            this.Test_Ocenjivanja = new HashSet<Test_Ocenjivanja>();
            this.Trening_Dani = new HashSet<Trening_Dani>();
            this.Trke_U_Sezoni = new HashSet<Trke_U_Sezoni>();
            this.Putanjas = new HashSet<Putanja>();
        }
    
        public long ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime Datum_Rodjenja { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public string Drzava { get; set; }
        public Nullable<long> Tezina { get; set; }
        public Nullable<long> Visina { get; set; }
        public string Omiljena_Trka_A { get; set; }
        public string Omiljena_Trka_B { get; set; }
        public string Omiljena_Trka_C { get; set; }
        public string Slika { get; set; }
        public string Zaposlenje { get; set; }
        public long ID_Nivo_Iskustva { get; set; }
    
        public virtual Iskustveni_Nivo Iskustveni_Nivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lista_Trka> Lista_Trka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mentalne_Sposobnosti> Mentalne_Sposobnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prirodne_Sposobnosti> Prirodne_Sposobnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profilisanje_Profila_Vozaca> Profilisanje_Profila_Vozaca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sezona> Sezonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprint_Test> Sprint_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Kriticne_Snage> Test_Kriticne_Snage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Ocenjivanja> Test_Ocenjivanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trening_Dani> Trening_Dani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trke_U_Sezoni> Trke_U_Sezoni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Putanja> Putanjas { get; set; }
    }
}
