//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glavni_Tipovi_Treninga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glavni_Tipovi_Treninga()
        {
            this.Tipovi_Treninga = new HashSet<Tipovi_Treninga>();
        }
    
        public long ID { get; set; }
        public string Naziv { get; set; }
        public long ID_Treniraj_ili_ne { get; set; }
    
        public virtual Treniraj_Ili_Ne Treniraj_Ili_Ne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipovi_Treninga> Tipovi_Treninga { get; set; }
    }
}
