//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nedelja
    {
        public long Broj_nedelje { get; set; }
        public System.DateTime Datum_pocetka { get; set; }
        public System.DateTime Datum_zavrsetka { get; set; }
        public long ID_Sezone { get; set; }
        public Nullable<long> ID_Trening_perioda { get; set; }
        public long ID_Bicikliste { get; set; }
        public string Opis { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
        public virtual Trening_Periodi Trening_Periodi { get; set; }
    }
}
