//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profilisanje_Profila_Vozaca
    {
        public System.DateTime Datum_testiranja { get; set; }
        public long ID_Bicikliste { get; set; }
        public int Brdo { get; set; }
        public int Sprint { get; set; }
        public int Hronometar { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
    }
}
