//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sezona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sezona()
        {
            this.Trening_Dani = new HashSet<Trening_Dani>();
            this.Trke_U_Sezoni = new HashSet<Trke_U_Sezoni>();
        }
    
        public long ID { get; set; }
        public long ID_Bicikliste { get; set; }
        public System.DateTime Datum_pocetka { get; set; }
        public Nullable<System.DateTime> Datum_zavrsetka { get; set; }
        public Nullable<int> Godina { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trening_Dani> Trening_Dani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trke_U_Sezoni> Trke_U_Sezoni { get; set; }
    }
}
