//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trke_U_Sezoni
    {
        public long ID_Sezone { get; set; }
        public long ID_Bicikliste { get; set; }
        public long ID_Trke { get; set; }
        public System.DateTime Datum_trke { get; set; }
        public string Prioritet { get; set; }
        public Nullable<int> Osvojeno_mesto { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
        public virtual Lista_Trka Lista_Trka { get; set; }
        public virtual Sezona Sezona { get; set; }
    }
}
