//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiciTrainingPlanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dnevni_Trening_Periodi : ITable
    {
        public long ID_Trening_period { get; set; }
        public long ID_Dana { get; set; }
        public long ID_Tipovi_treninga { get; set; }
    
        public virtual Dani Dani { get; set; }
        public virtual Tipovi_Treninga Tipovi_Treninga { get; set; }
        public virtual Trening_Periodi Trening_Periodi { get; set; }
    }
}
