//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiciTrainingPlanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_Trka : ITable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lista_Trka()
        {
            this.Trke_U_Sezoni = new HashSet<Trke_U_Sezoni>();
        }
    
        public long ID { get; set; }
        public string Naziv_trke { get; set; }
        public long ID_Putanje { get; set; }
        public long ID_Bicikliste { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
        public virtual Putanja Putanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trke_U_Sezoni> Trke_U_Sezoni { get; set; }
    }
}
