//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiciTrainingPlanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprint_Test : ITable
    {
        public System.DateTime Datum_testiranja { get; set; }
        public long ID_Bicikliste { get; set; }
        public int Maksimalna_Snaga { get; set; }
        public int Prosecna_Snaga { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
    }
}
