//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiciTrainingPlanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Kriticne_Snage : ITable
    {
        public System.DateTime Datum_testiranja { get; set; }
        public long ID_Bicikliste { get; set; }
        public int CP0 { get; set; }
        public int CP1 { get; set; }
        public int CP6 { get; set; }
        public int CP12 { get; set; }
        public int CP30 { get; set; }
        public int CP60 { get; set; }
        public int CP90 { get; set; }
        public int CP180 { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
    }
}
