//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiciTrainingPlanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trening_Dani
    {
        public long ID_Bicikliste { get; set; }
        public System.DateTime Datum_treninga { get; set; }
        public long ID_Nedelje { get; set; }
        public long ID_Treninga { get; set; }
        public long ID_Putanje { get; set; }
        public string Vreme_treninga { get; set; }
        public Nullable<int> Prosecna_brzina { get; set; }
        public Nullable<int> Maksimalna_brzina { get; set; }
        public Nullable<int> Distanca { get; set; }
        public Nullable<int> Nadmorska_visina { get; set; }
        public Nullable<int> Prosecna_snaga { get; set; }
        public Nullable<int> Makimalna_snaga { get; set; }
        public Nullable<int> Prosecni_otkucaji_srca { get; set; }
        public Nullable<int> Maksimalni_otkucaji_srca { get; set; }
        public Nullable<int> Jutarnji_otkucaji_srca { get; set; }
        public Nullable<int> Subjektivni_osecaj_pre_treninga { get; set; }
        public Nullable<int> Subjektivni_osecaj_posle_treninga { get; set; }
    
        public virtual Biciklista Biciklista { get; set; }
        public virtual Nedelja Nedelja { get; set; }
        public virtual Putanja Putanja { get; set; }
    }
}
